import { API } from "@/constants/api";

export const AUTH_ENDPOINTS = {
  LOGIN: API.AUTH.LOGIN,
  REGISTER: API.AUTH.REGISTER,
  LOGOUT: API.AUTH.LOGOUT,
  REFRESH: API.AUTH.REFRESH,
  VERIFY_EMAIL: API.AUTH.VERIFY_EMAIL,
  FORGOT_PASSWORD: API.AUTH.FORGOT_PASSWORD,
  RESET_PASSWORD: API.AUTH.RESET_PASSWORD,
  PROFILE: API.AUTH.PROFILE,
};