# Generated by Django 4.2.30 on 2026-07-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='hero/')),
                ('button_one_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_one_link', models.CharField(default='/products', max_length=100)),
                ('button_two_text', models.CharField(default='Explore', max_length=50)),
                ('button_two_link', models.CharField(default='/categories', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
